DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS sensors CASCADE;
DROP TABLE IF EXISTS sensor_data CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE sensors (
  id SERIAL PRIMARY KEY NOT NULL,
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  users_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE sensor_data (
  id SERIAL PRIMARY KEY NOT NULL,
  sensors_id INTEGER REFERENCES sensors(id) ON DELETE CASCADE,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  co2 INTEGER NOT NULL,
  tvoc INTEGER NOT NULL
);

CREATE TABLE alerts (
  id SERIAL PRIMARY KEY NOT NULL,
  sensors_id INTEGER REFERENCES sensors(id) ON DELETE CASCADE,
  users_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);